### ISSUE TITLE
Can't play video on Android

### ISSUE THREAD

**Issue by sergiy-talashko** [fubotv/ooyala-IMA-SDK-phonegap-wrapper#4]
This is what I get on browse console:

````
---PLAYER IS CREATED SUCCESSFULLY--- root.js:325
processMessage failed: Error: TypeError: Cannot call method 'forEach' of undefined cordova.js:1059
processMessage failed: Stack: TypeError: Cannot call method 'forEach' of undefined
    at MessageBus.handler (file:///android_asset/www/plugins/com.fubotv.cordova.ooyalaIMAPlugin/www/ooyala_player.js:160:35)
    at Object.cordova.callbackFromNative (file:///android_asset/www/cordova.js:293:54)
    at processMessage (file:///android_asset/www/cordova.js:1054:21)
    at Function.androidExec.processMessages (file:///android_asset/www/cordova.js:1091:13)
    at pollOnce (file:///android_asset/www/cordova.js:956:17)
    at pollOnceFromOnlineEvent (file:///android_asset/www/cordova.js:946:5) cordova.js:1060
processMessage failed: Message: S11 OoyalaIMA1838537958 {"event":"DOWNLOADING"} cordova.js:1061
processMessage failed: Error: TypeError: Cannot call method 'forEach' of undefined cordova.js:1059
processMessage failed: Stack: TypeError: Cannot call method 'forEach' of undefined
    at MessageBus.handler (file:///android_asset/www/plugins/com.fubotv.cordova.ooyalaIMAPlugin/www/ooyala_player.js:160:35)
    at Object.cordova.callbackFromNative (file:///android_asset/www/cordova.js:293:54)
    at processMessage (file:///android_asset/www/cordova.js:1054:21)
    at Function.androidExec.processMessages (file:///android_asset/www/cordova.js:1091:13)
    at pollOnce (file:///android_asset/www/cordova.js:956:17)
    at pollOnceFromOnlineEvent (file:///android_asset/www/cordova.js:946:5) cordova.js:1060
processMessage failed: Message: S11 OoyalaIMA1838537958 {"event":"FULLSCREEN_CHANGED","params":true} cordova.js:1061
processMessage failed: Error: TypeError: Cannot call method 'forEach' of undefined cordova.js:1059
processMessage failed: Stack: TypeError: Cannot call method 'forEach' of undefined
    at MessageBus.handler (file:///android_asset/www/plugins/com.fubotv.cordova.ooyalaIMAPlugin/www/ooyala_player.js:160:35)
    at Object.cordova.callbackFromNative (file:///android_asset/www/cordova.js:293:54)
    at processMessage (file:///android_asset/www/cordova.js:1054:21)
    at Function.androidExec.processMessages (file:///android_asset/www/cordova.js:1091:13)
    at pollOnce (file:///android_asset/www/cordova.js:956:17)
    at pollOnceFromOnlineEvent (file:///android_asset/www/cordova.js:946:5) cordova.js:1060
processMessage failed: Message: S11 OoyalaIMA1838537958 {"event":"METADATA_FETCHED"} cordova.js:1061
processMessage failed: Error: TypeError: Cannot call method 'forEach' of undefined cordova.js:1059
processMessage failed: Stack: TypeError: Cannot call method 'forEach' of undefined
    at MessageBus.handler (file:///android_asset/www/plugins/com.fubotv.cordova.ooyalaIMAPlugin/www/ooyala_player.js:160:35)
    at Object.cordova.callbackFromNative (file:///android_asset/www/cordova.js:293:54)
    at processMessage (file:///android_asset/www/cordova.js:1054:21)
    at Function.androidExec.processMessages (file:///android_asset/www/cordova.js:1091:13)
    at pollOnce (file:///android_asset/www/cordova.js:956:17)
    at pollOnceFromOnlineEvent (file:///android_asset/www/cordova.js:946:5) cordova.js:1060
processMessage failed: Message: S11 OoyalaIMA1838537958 {"event":"EMBED_CODE_CHANGED","params":"Vncjl3cDqXf2fci9bP4sqvU-VM8kY7tv"}
````

Device: Nexus 7, Android 4.4.4

**Comment by sergiy-talashko** [comment]
Hi DongKai.
Yes, write me when you will be available.

P.S. My best wishes for a healthy and happy New Year!

**Comment by fenghuang86** [comment]
Hi. Sergiy.

Happy New Year!
Wish your happiness and success in the business.
I am now available. let me know if we can work together in this afternoon or tonight.

Kind Regards.
DongKai.

**Comment by fenghuang86** [comment]
Hi.

seems you missed the following line before method implementation.
@Override

Thanks.
DongKai.

**Comment by sergiy-talashko** [comment]
Hi. 

I added "@Override" line in to main java file, but it's not helped - app minimize after clicking back button.
I pull this changes into git. Could you check this again?

**Comment by fenghuang86** [comment]
Hi.

sorry for the late answer.
I will review my code soon.

**Comment by fenghuang86** [comment]
Hi. Serigey.

I did pull the latest repository, build the apk, and test on my nexus 4 phone.
but I can't replicate the bug. let me know the steps you did undertake.

Thanks.

**Comment by sergiy-talashko** [comment]
Here video of my testing - http://youtu.be/AeLadjCNVGg

1. After first clicking back button video rotate to portrait mode, but video is not hide or stop.
2. Then I trying clicking on resize button - to watch what it does.
3. After second clicking on back button - app is minimize.

Could you also send me your APK file for testing.

**Comment by fenghuang86** [comment]
Hi. Sergiey.

I did find one thing.
When tapping video, black screen with white close button (X) is shown, which is not a thing that is made by Ooyala player. I think that view does do tricks and generate such the bug.

I think the black screen is old implementation and you may forgot to remove it.. :) 
Could you please review the code and try again?

On my side, I did test the plugin usage with new project and the plugin worked well on my devices.
In one word, at the moment I have a doubt about the black screen.

Let me know your thoughts.
Kind Regards.
DongKai.

**Comment by sergiy-talashko** [comment]
Hi, DongKai. 

There are no white close button on my test video. 
If you test project https://github.com/fubotv/enduser_mobile you should switch to "ooyala-wrapper" branch, because yes - master branch has old implementation.

Regarding your apk - you created new project that doesn't have plugins that we use. Maybe that's a reason? 
Could you please send me your test apk for testing? If it will work good, then we can decide, that problem in compatibility of plugins.

Best regards,
Sergiy Talashko

**Comment by fenghuang86** [comment]
Hi. Sergiy.

Here is testing apk.
https://www.sendspace.com/file/6f8ovh

Thanks.
DongKai.

**Comment by sergiy-talashko** [comment]
Yes, problem in incompatibility of plugins. Ionic or InAppBrowser plugin rewrite your function for back button. 
Good news that I can handle clicking on back button from js. 
Could you create method player.close() or player.destroy() so I can close and destroy player from js?
